version: "3"

services:
  api:
    build: .
    ports:
      - 9090:9090

  mongodb1:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data:
